# Generated by Django 4.1.1 on 2022-09-21 09:11

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=re.RegexFlag['TEMPLATE'], null=True, upload_to=''),
        ),
    ]
